[project]
name = "demo"
version = "0.1"
requires-python = ">=3.11,<4"
dependencies = [
  "requests[socks]==2.34.2",
  "typer==0.21.0 ; python_version >= '3.11'",
  "iniconfig @ git+https://github.com/pytest-dev/iniconfig@v2.0.0",
  "six @ https://files.pythonhosted.org/packages/b7/ce/149a00dd41f10bc29e5921b496af8b574d8413afcd5e30dfa0ed46c2cc5e/six-1.17.0-py2.py3-none-any.whl",
]
[tool.poetry]
package-mode = false
[tool.poetry.dependencies]
localpkg = { path = "localpkg", develop = true }
